-- =============================================================
-- Scheduled automation
--
-- Until now three pieces of housekeeping only happened when a
-- manager happened to open a page:
--   • rent invoices were generated by hand (bulk modal)
--   • overdue flagging ran client-side on the Invoices page
--   • lease statuses never advanced on their own
--
-- This migration moves all of that server-side and runs it on a
-- daily pg_cron schedule, so the product keeps itself current with
-- nobody logged in. Each job is an idempotent SECURITY DEFINER
-- function; an orchestrator runs them in the correct order and logs
-- the outcome to automation_runs for visibility.
-- =============================================================

create extension if not exists pg_cron;

-- Hardens idempotency: one invoice per (lease, period). Lets the
-- generators use ON CONFLICT and makes the manual bulk path race-safe.
create unique index if not exists invoices_lease_period_uniq
  on invoices (lease_id, period_start);

-- ---------- run log ----------
create table if not exists automation_runs (
  id                uuid primary key default gen_random_uuid(),
  ran_at            timestamptz not null default now(),
  source            text not null default 'cron',  -- 'cron' | 'manual'
  invoices_created  int not null default 0,
  leases_activated  int not null default 0,
  leases_expired    int not null default 0,
  invoices_flagged  int not null default 0
);

alter table automation_runs enable row level security;
-- Operational metadata (counts + timestamps only): any manager may read.
drop policy if exists automation_runs_read on automation_runs;
create policy automation_runs_read on automation_runs
  for select using (is_manager());

-- ---------- jobs ----------

-- upcoming -> active once the start date arrives (and it hasn't ended).
create or replace function activate_pending_leases()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare n int;
begin
  update leases
     set status = 'active'
   where status = 'upcoming'
     and start_date <= current_date
     and end_date   >= current_date;
  get diagnostics n = row_count;
  return n;
end;
$$;

-- active -> expired once the end date has passed.
create or replace function expire_ended_leases()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare n int;
begin
  update leases
     set status = 'expired'
   where status = 'active'
     and end_date < current_date;
  get diagnostics n = row_count;
  return n;
end;
$$;

-- sent -> overdue once the due date has passed.
create or replace function flag_overdue_invoices()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare n int;
begin
  update invoices
     set status = 'overdue'
   where status = 'sent'
     and due_date < current_date;
  get diagnostics n = row_count;
  return n;
end;
$$;

-- Generate any missing rent invoices for active leases, for every
-- billing period that has already started. Mirrors the client-side
-- computeDuePeriods(): step by the lease frequency from the start
-- date, stop at today or the lease end, due_date = period_start,
-- and a period that started before today lands as 'overdue'.
create or replace function generate_due_invoices()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v       record;
  v_step  int;
  v_ps    date;
  v_pe    date;
  v_today date := current_date;
  v_total int := 0;
  v_n     int;
begin
  for v in
    select id, org_id, start_date, end_date, rent_amount, frequency, currency
    from leases
    where status = 'active'
  loop
    v_step := case v.frequency
      when 'monthly'    then 1
      when 'quarterly'  then 3
      when 'semiannual' then 6
      else 12
    end;
    v_ps := v.start_date;
    -- 240 = defensive cap (20 years of monthly periods), matching the client.
    for i in 0..239 loop
      exit when v_ps > v_today or v_ps > v.end_date;
      v_pe := (v_ps + make_interval(months => v_step))::date;
      insert into invoices (org_id, lease_id, period_start, period_end,
                            amount, currency, due_date, status)
      values (v.org_id, v.id, v_ps, v_pe,
              v.rent_amount, v.currency, v_ps,
              (case when v_ps < v_today then 'overdue' else 'sent' end)::invoice_status)
      on conflict (lease_id, period_start) do nothing;
      get diagnostics v_n = row_count;
      v_total := v_total + v_n;
      v_ps := v_pe;
    end loop;
  end loop;
  return v_total;
end;
$$;

-- Orchestrator: order matters. Activate first so newly-active leases
-- get invoiced this run; generate before expiring so a just-ended
-- lease's final period is still created while it is active.
create or replace function run_scheduled_jobs(p_source text default 'cron')
returns automation_runs
language plpgsql
security definer
set search_path = public
as $$
declare
  v_activated int;
  v_created   int;
  v_flagged   int;
  v_expired   int;
  rec automation_runs;
begin
  v_activated := activate_pending_leases();
  v_created   := generate_due_invoices();
  v_flagged   := flag_overdue_invoices();
  v_expired   := expire_ended_leases();

  insert into automation_runs (source, invoices_created, leases_activated,
                               leases_expired, invoices_flagged)
  values (p_source, v_created, v_activated, v_expired, v_flagged)
  returning * into rec;
  return rec;
end;
$$;

-- Manager-facing "Run now". Guarded by is_manager() so the cron path
-- (which has no auth context) keeps using run_scheduled_jobs directly.
create or replace function trigger_scheduled_jobs()
returns automation_runs
language plpgsql
security definer
set search_path = public
as $$
declare rec automation_runs;
begin
  if not is_manager() then
    raise exception 'only managers can run automation';
  end if;
  rec := run_scheduled_jobs('manual');
  return rec;
end;
$$;

revoke all on function run_scheduled_jobs(text) from public;
revoke all on function trigger_scheduled_jobs() from public;
grant execute on function trigger_scheduled_jobs() to authenticated;

-- ---------- schedule (daily 02:00 UTC = 06:00 Asia/Dubai) ----------
select cron.unschedule('frontbits-daily-automation')
where exists (select 1 from cron.job where jobname = 'frontbits-daily-automation');

select cron.schedule(
  'frontbits-daily-automation',
  '0 2 * * *',
  $job$ select public.run_scheduled_jobs('cron'); $job$
);
